security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker # <-- Ajoute cette ligne pour lier ton checker

            # Configuration pour React
            json_login:
                check_path: api_login        # La route que React appellera
                username_path: email         # Le champ JSON contenant l'identifiant
                password_path: password      # Le champ JSON contenant le mdp
            
            logout:
                path: api_logout             # La route pour se dÃ©connecter


    # Activate different ways to authenticate:
    # https://symfony.com/doc/current/security.html#the-firewall

    # https://symfony.com/doc/current/security/impersonating_user.html
    # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: /api/logout, roles: ROLE_USER }
        - { path: /api/user/patch-params, roles: ROLE_USER }
        - { path: /api/user/patch-email, roles: ROLE_USER }
        - { path: /api/user/patch-password, roles: ROLE_USER }
        - { path: /api/user/email-not-used, roles: ROLE_USER }
        - { path: /api/user/send-email-with-code, roles: ROLE_USER }

        - { path: /api/me, roles: PUBLIC_ACCESS }
        - { path: /api/login, roles: PUBLIC_ACCESS}
        - { path: /api/refresh, roles: PUBLIC_ACCESS}
        - { path: /api/verify, roles: PUBLIC_ACCESS}
        - { path: /api/register, roles: PUBLIC_ACCESS}
        - { path: /api/user/email-used, roles: PUBLIC_ACCESS }
        - { path: /api/user/send-code-for-password, roles: PUBLIC_ACCESS }
        - { path: /api/user/verify-code-for-password, roles: PUBLIC_ACCESS }
        - { path: /api/user/patch-forgot-password, roles: PUBLIC_ACCESS }

        - { path: /api/julia-fractal/get-all, roles: ROLE_ADMIN }
        - { path: /api/user/get-all, roles: ROLE_ADMIN }

        - { path: /api/julia-fractal/get-from-current-user, roles: ROLE_USER }
        - { path: /api/julia-fractal/get-public, roles: PUBLIC_ACCESS }
        - { path: /api/julia-fractal/get-without-user, roles: PUBLIC_ACCESS }
        - { path: /api/julia-fractal/add-to-user, roles: ROLE_USER }
        - { path: /api/julia-fractal/delete-from-user, roles: ROLE_USER }
        - { path: /api/julia-fractal/create-to-user, roles: ROLE_USER }

        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
